# Generated by Django 4.0.2 on 2022-04-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='记录号')),
                ('w_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='委托书月份')),
                ('c_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='出本月份')),
                ('p_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='工程编号')),
                ('p_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='工程名称')),
                ('xx_road', models.CharField(blank=True, db_column='XX路XX机房', max_length=255, null=True, verbose_name='xx路xx机房')),
                ('number_twelve', models.CharField(blank=True, db_column='12芯光缆长度', max_length=255, null=True, verbose_name='12芯光缆长度')),
                ('l_box_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='光分箱数量')),
                ('ways', models.CharField(blank=True, max_length=255, null=True, verbose_name='敷设方式')),
                ('d_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='设计编号')),
                ('p_totle', models.CharField(blank=True, max_length=255, null=True, verbose_name='工程总价')),
                ('p_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='工程费')),
                ('l_box_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='光分箱造价')),
                ('oc_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='光缆造价')),
                ('fixed', models.CharField(blank=True, max_length=255, null=True, verbose_name='固定部分')),
                ('explore_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='勘察设计费')),
                ('monitor_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='监理费')),
                ('jiheyiben', models.CharField(blank=True, max_length=255, null=True, verbose_name='几合一本')),
                ('l_box', models.CharField(blank=True, max_length=255, null=True, verbose_name='光交箱')),
                ('box_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='箱号')),
                ('tiao_km', models.CharField(blank=True, max_length=255, null=True, verbose_name='条公里')),
                ('twelve_c_km', models.CharField(blank=True, db_column='生产能力12C芯公里', max_length=255, null=True, verbose_name='生产能力12c芯公里')),
                ('xin_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='芯公里造价')),
            ],
            options={
                'db_table': 'pro_info',
                'managed': True,
            },
        ),
    ]
