# Generated by Django 4.0.2 on 2022-04-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proinfo',
            old_name='xx_road',
            new_name='jifang',
        ),
        migrations.RemoveField(
            model_name='proinfo',
            name='c_month',
        ),
        migrations.RemoveField(
            model_name='proinfo',
            name='jiheyiben',
        ),
        migrations.RemoveField(
            model_name='proinfo',
            name='w_month',
        ),
    ]
