# Generated by Django 4.0.2 on 2022-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_xx_road_proinfo_jifang_remove_proinfo_c_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proinfo',
            name='record_id',
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='box_number',
            field=models.CharField(max_length=255, null=True, verbose_name='箱号'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='d_id',
            field=models.CharField(max_length=255, verbose_name='设计编号'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='explore_price',
            field=models.IntegerField(default=1000, verbose_name='勘察设计费'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='fixed',
            field=models.IntegerField(default=2700, max_length=255, verbose_name='固定部分'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='jifang',
            field=models.CharField(max_length=255, verbose_name='xx路xx机房'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='l_box',
            field=models.CharField(max_length=255, verbose_name='光交箱'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='l_box_number',
            field=models.IntegerField(default=1, verbose_name='光分箱数量'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='l_box_price',
            field=models.CharField(max_length=255, verbose_name='光分箱造价'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='monitor_price',
            field=models.IntegerField(default=300, verbose_name='监理费'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='number_twelve',
            field=models.IntegerField(verbose_name='12芯光缆长度'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='oc_price',
            field=models.CharField(max_length=255, verbose_name='光缆造价'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='p_id',
            field=models.CharField(max_length=255, verbose_name='工程编号'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='p_name',
            field=models.CharField(max_length=255, verbose_name='工程名称'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='p_price',
            field=models.CharField(max_length=255, verbose_name='工程费'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='p_totle',
            field=models.CharField(max_length=255, verbose_name='工程总价'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='tiao_km',
            field=models.CharField(max_length=255, verbose_name='条公里'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='twelve_c_km',
            field=models.CharField(db_column='生产能力12C芯公里', max_length=255, verbose_name='生产能力12c芯公里'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='ways',
            field=models.CharField(default=1, max_length=255, verbose_name='敷设方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='xin_price',
            field=models.CharField(default=1, max_length=255, verbose_name='芯公里造价'),
            preserve_default=False,
        ),
    ]
