# Generated by Django 4.0.2 on 2022-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_proinfo_record_id_alter_proinfo_box_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proinfo',
            name='box_number',
            field=models.CharField(default=2, max_length=255, verbose_name='箱号'),
            preserve_default=False,
        ),
    ]
