# Generated by Django 4.0.2 on 2022-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_proinfo_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proinfo',
            name='fixed',
            field=models.IntegerField(default=2700, verbose_name='固定部分'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='tiao_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='条公里'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='twelve_c_km',
            field=models.DecimalField(db_column='生产能力12C芯公里', decimal_places=2, max_digits=10, verbose_name='生产能力12c芯公里'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='xin_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='芯公里造价'),
        ),
    ]
