# Generated by Django 4.0.2 on 2022-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='optical_direction',
        ),
        migrations.AlterField(
            model_name='box',
            name='available',
            field=models.IntegerField(blank=True, null=True, verbose_name='空闲'),
        ),
        migrations.AlterField(
            model_name='box',
            name='occupancy',
            field=models.IntegerField(blank=True, null=True, verbose_name='占用'),
        ),
        migrations.AlterField(
            model_name='box',
            name='terminal_f',
            field=models.IntegerField(blank=True, null=True, verbose_name='空闲端子数'),
        ),
        migrations.AlterField(
            model_name='box',
            name='terminal_n',
            field=models.IntegerField(blank=True, null=True, verbose_name='总端子数'),
        ),
        migrations.AlterField(
            model_name='box',
            name='totle_wick',
            field=models.IntegerField(blank=True, null=True, verbose_name='总芯数'),
        ),
        migrations.AlterField(
            model_name='proinfo',
            name='ways',
            field=models.IntegerField(choices=[(1, '管道及钉固'), (2, '管道、挂墙及钉固'), (3, '管道及挂墙'), (4, '钉固'), (5, '架空、管道及钉固'), (6, '架空、管道、挂墙及钉固'), (7, '挂墙'), (8, '挂墙及钉固'), (9, '架空、管道及挂墙'), (10, '架空及挂墙'), (11, '架空及管道')], verbose_name='敷设方式'),
        ),
    ]
